name: GhostSignal Uplink
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allows you to trigger it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests
          echo "--- VERIFYING LIBRARIES ---"
          pip list | grep -E "requests|feedparser"
        
      - name: Run Decoder
        run: python fetch_signals.py
        
      - name: Commit and Push
        run: |
          git config --global user.name 'GhostSignal-Bot'
          git config --global user.email 'bot@ghostsignal.net'
          git add signals.js
          git commit -m "STABLE_UPLINK: $(date)" || echo "No changes"
          git pull --rebase --autostash origin main
          git push origin main
